

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.joda.time.DateTime;
import org.lib.helper.ConnectionManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nitin Singla
 */
public class InvoiceNew extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceNew
     */
    public InvoiceNew() {
        initComponents();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((d.width/2-getWidth()/2),(d.height/2-getHeight()/2));
       jDateChooser2.setEnabled(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jComboBox5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField8.setVisible(false);
       
        getclientcategory();
        getInvoiceID();
        getproductcategory();

      DateTime today = new DateTime();

        jDateChooser1.setDate(today.toDate());
       
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        
        String duedate=jComboBox2.getSelectedItem().toString();
        if(duedate.equals("Net 10"))
        {
//            DateFormat datedue = new SimpleDateFormat("yyyy/MM/dd");
//     Date newDate = new Date();
//    newDate.setDate(newDate.getDate()+1);

      DateTime tomorrow = today.plusDays(10);
       jDateChooser2.setDate(tomorrow.toDate());
        }
    }
    
      private void getInvoiceID()
      {
          String sql="select max(invoiceno) from inventory";
          int mid = 0;
          try
          {
              c = ConnectionManager.getConnection();
              ps = c.prepareStatement(sql);
              ResultSet rs = ps.executeQuery();
              while(rs.next())
              {
                  mid = rs.getInt(1);
              }
          }catch(Exception e)
          {
              e.printStackTrace();
          }
          jTextField2.setText(""+(mid+1));
          jTextField2.setEnabled(false);
      }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Invoice");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Invoice Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("P.O. Number");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField2.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Issue date");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Payment Terms");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Due Date");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Net 10", "Net 15", "Net 30", "Net 45", "Net 60", "Net 90", "Due on Reciept", "Due on Specified Date" }));
        jComboBox2.setSelectedIndex(6);
        jComboBox2.setToolTipText("Selecting a payment term will recalculate the Due Date");
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----Select Client Type-----", "<Add New Client>" }));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox1KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Client");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Invoice Data");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Product/Service");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 216, 132, 40));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----Select Product Type-----" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jComboBox3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox3KeyTyped(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 262, 228, 29));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Description");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 225, 131, -1));

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 262, 167, 29));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Quantity");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 80, 26));

        jTextField4.setForeground(new java.awt.Color(153, 153, 255));
        jTextField4.setText("Sell QTY");
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 263, 71, 29));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Unit Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 224, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 262, 83, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("TAX");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 222, 100, -1));

        jComboBox4.setEditable(true);
        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4%", "5%", "1%", "2%", "Add New" }));
        jComboBox4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox4PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 263, 105, 29));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 263, 120, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Product/Service", "Description", "QTY", "Unit Price", "Value", "Tax", "Edit", "Delete"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(30);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        jTable1.getColumnModel().getColumn(1).setMinWidth(200);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(200);
        jTable1.getColumnModel().getColumn(3).setMinWidth(50);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(50);
        jTable1.getColumnModel().getColumn(6).setMinWidth(100);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(7).setMinWidth(100);
        jTable1.getColumnModel().getColumn(7).setMaxWidth(100);
        jTable1.getColumnModel().getColumn(8).setMinWidth(100);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(100);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 309, 935, 130));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton1.setText("Mark Invoice Paid");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 456, -1, -1));

        jLabel17.setFont(new java.awt.Font("Shruti", 0, 14)); // NOI18N
        jLabel17.setText("Payment Type");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 458, 90, 25));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit Card", "Check", "Bank Transfer", "Other" }));
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 456, 106, 26));

        jLabel16.setFont(new java.awt.Font("Shruti", 0, 14)); // NOI18N
        jLabel16.setText("Amount Paid");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 80, 30));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 106, 29));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRadioButton2.setText("Get Paid Online (PayPal)");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, -1));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 180, 63));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Invoice Notes");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 123, 20));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Private Notes");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 90, 20));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane6.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 180, 63));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Save and Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 198, -1));

        jTextField7.setEditable(false);
        jTextField7.setForeground(new java.awt.Color(153, 153, 255));
        jTextField7.setText("Max. QTY");
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 263, 71, 29));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 30, 20));

        jLabel19.setText("Subtotal");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 447, 83, 22));

        jLabel20.setText("General Tax");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 480, 83, 22));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 447, 113, 22));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 480, 113, 22));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Total");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 524, 83, 22));
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 554, 113, 22));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 508, 214, 10));
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 524, 113, 22));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setText("Quantity");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 234, 80, 22));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setText("Stock");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 239, 80, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Preview Invoice");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 610, 198, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox4PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox4PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        comboselect();
    }//GEN-LAST:event_jComboBox4PopupMenuWillBecomeInvisible

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    public void comboselect()
    {
     int d=jComboBox4.getSelectedIndex();
     if(jComboBox4.getSelectedItem()=="Add New")
        {
     NewTax tx=new NewTax();
       tx.setVisible(true);
        }
    }

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isEnabled())
        {
            jLabel16.setVisible(true);
            jLabel17.setVisible(true);
            jComboBox5.setVisible(true);
            jTextField6.setVisible(true);
        }
        else
        {
            jLabel16.setVisible(false);
             jLabel16.setVisible(false);
            jComboBox5.setVisible(false);
            jTextField6.setVisible(false);
            jTextField6.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

 
        String client=jComboBox1.getSelectedItem().toString();
        
        
        if(client.equals("-----Select Client Type-----"))
        {
        
        JOptionPane.showMessageDialog(rootPane, "Please Select a client for Your Invoice");
        //jButton2.setEnabled(false);
        }
        else{
              for(int i=0;i< jTable1.getRowCount();i++){
       
        jButton2.setEnabled(true);
        String invoice=jTextField2.getText();
        String issue=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String ponumber=jTextField1.getText();
        String payterm=jComboBox2.getSelectedItem().toString();
        String duedate=((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
        String producttype=jComboBox3.getSelectedItem().toString();
        String des=jTextField3.getText();
        String qty=jTextField4.getText();
        String uprice=jTextField5.getText();
        String tax=jComboBox4.getSelectedItem().toString();
        BigInteger num1=new BigInteger(qty);
        BigInteger num2=new BigInteger(uprice);
        BigInteger value=num1.multiply(num2);
        String sql="insert into invoice values(?,?,?,?,?,?,?,?,?,?,?,?)";
        try
        {
        c=ConnectionManager.getConnection();
        ps=c.prepareStatement(sql);
        ps.setString(1,client);    
        ps.setString(2,invoice);  
        ps.setString(3,issue);
        ps.setString(4,ponumber); 
        ps.setString(5, payterm);
        ps.setString(6, duedate);
        ps.setString(7, producttype);
        ps.setString(8, des);
        ps.setString(9, qty);
        ps.setString(10, uprice);
        ps.setString(11, tax);
        ps.setString(12, value.toString());
        int n=ps.executeUpdate();
        if(n==1)
        {
//            jTextField1.setText("");
//            jTextField2.setText("");
//            jTextField3.setText("");
//            jTextField4.setText("");
        }
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(null,"Error : "+ e.getMessage(),"Error",0);
        }
        }
             }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isEnabled())
        {
           jLabel16.setVisible(false);
           jLabel17.setVisible(false);
           jComboBox5.setVisible(false);
           jTextField6.setVisible(false);
           
        }
        else
        {
            jLabel16.setVisible(false);
             jLabel16.setVisible(false);
            jComboBox5.setVisible(false);
            jTextField6.setVisible(false);
            jTextField6.setVisible(false);
        
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
      int a=jComboBox1.getSelectedIndex();
     if(a==1)
     {
     NewClients nc=new NewClients();
     nc.setVisible(true);
     }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

   Connection c=null;
   PreparedStatement ps=null;
    
    
    private void getclientcategory()
    {
    String sql="select * from cust_mstr";
    try
    {
    c= ConnectionManager.getConnection();
    PreparedStatement ps=c.prepareStatement(sql);
        ResultSet rs=ps.executeQuery();
        while(rs.next())
        {
        jComboBox1.addItem(rs.getString(2));
        }
    }catch(Exception e)
    {
        System.out.println(e.getMessage());
    }
    }
    
    private void getproductcategory()
    {
    String sql="select * from product";
    try
    {
    c= ConnectionManager.getConnection();
    PreparedStatement ps=c.prepareStatement(sql);
        ResultSet rs=ps.executeQuery();
        while(rs.next())
        {
        jComboBox3.addItem(rs.getString(2));
        }
    }catch(Exception e)
    {
        System.out.println(e.getMessage());
    }
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String item=(String) jComboBox1.getSelectedItem();
        System.out.println(item);
        
        String sql="select Address from cust_mstr where Name =?";
    try
    {
    c= ConnectionManager.getConnection();
    PreparedStatement ps=c.prepareStatement(sql);
    ps.setString(1, item);
        ResultSet rs=ps.executeQuery();
        while(rs.next())
        {
        jLabel18.setText(rs.getString(1));
        }
    }catch(Exception e)
    {
        System.out.println(e.getMessage());
    }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        String item=(String) jComboBox3.getSelectedItem();
        System.out.println(item);
        
        String sql="select Description from product where Pname =?";
    try
    {
    c= ConnectionManager.getConnection();
    PreparedStatement ps=c.prepareStatement(sql);
    ps.setString(1, item);
        ResultSet rs=ps.executeQuery();
        while(rs.next())
        {
        jTextField3.setText(rs.getString(1));
        jTextField4.setText("1");
        }
    }catch(Exception e)
    {
        System.out.println(e.getMessage());
    }
    
    
    String sql1="select quantity,price from inventory where pname =?";
    try
    {
    c= ConnectionManager.getConnection();
    PreparedStatement ps=c.prepareStatement(sql1);
    ps.setString(1, item);
        ResultSet rs=ps.executeQuery();
        while(rs.next())
        {
        jTextField7.setText(rs.getString(1));
        jTextField5.setText(rs.getString(2));
        }
    }catch(Exception e)
    {
        System.out.println(e.getMessage());
    }
    jButton1.requestFocus();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox3KeyTyped
        // TODO add your handling code here:
        AutoCompletion.enable(jComboBox3);
    }//GEN-LAST:event_jComboBox3KeyTyped

    private void jComboBox1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyTyped
        // TODO add your handling code here:
        AutoCompletion.enable(jComboBox1);
    }//GEN-LAST:event_jComboBox1KeyTyped
int flag=0;
    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        flag=flag+1;
       if(flag==1){
       jTextField4.setText("");
       flag=flag+1;
       if(flag>1){
       Font gainFont = new Font("Tahoma", Font.PLAIN, 16);  
       jTextField4.setFont(gainFont);  
       jTextField4.setForeground(Color.BLACK); 
       }
        flag=-50;
       } 
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //Getting pid from ptype
        String ptypes=jComboBox3.getSelectedItem().toString();
        String sql1="select pid from product where pname=?";
         try
    {
    c= ConnectionManager.getConnection();
    PreparedStatement ps=c.prepareStatement(sql1);
    ps.setString(1,ptypes);
        ResultSet rs=ps.executeQuery();
        while(rs.next())
        {
        jTextField8.setText(rs.getString(1));
        }
    }catch(Exception e)
    {
        System.out.println(e.getMessage());
    }
        
        String pid=jTextField8.getText();  
        String invoice=jTextField2.getText();  
        String issue=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String ptype=jComboBox3.getSelectedItem().toString();
        String des=jTextField3.getText();  
        String qty=jTextField4.getText();  
        String uprice =jTextField5.getText();  

    BigInteger num1=new BigInteger(qty);
    BigInteger num2=new BigInteger(uprice);
    BigInteger value=num1.multiply(num2);
    
        String tax=jComboBox4.getSelectedItem().toString();
        tax = tax.replace("%","");
        int taxes=Integer.parseInt(tax);
        float taxs=(float) (taxes * Integer.parseInt(uprice) * .01);
        
       
        System.out.println(taxs);
        String sql="insert into inventory(pid,transactiondate,invoiceno,pname,price ) values(?,?,?,?,?)";
        try
        {
        c=ConnectionManager.getConnection();
        ps=c.prepareStatement(sql);
        ps.setString(1,pid);    
        ps.setString(2, issue);  
        ps.setString(3, invoice);
        ps.setString(4,ptype); 
        ps.setString(5,uprice);
        int n=ps.executeUpdate();
        if(n==1)
        {

//            jTextField3.setText("");
//            jTextField4.setText("");
//            jTextField5.setText("");
            
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        
        int srn=tm.getRowCount()+1;

            Object[] newRow = {srn,ptype,des,qty,uprice,value,taxs};
                tm.addRow(newRow);

               jLabel19.setVisible(true);
                jLabel20.setVisible(true);
                 jLabel21.setVisible(true);
                  jLabel22.setVisible(true);;
//                  
//                    for(int i=0;i< jTable1.getRowCount();i++){
//        for (int j=5;j<jTable1.getColumnCount();j++){
//            
//            //int quantity = 
//BigInteger quantity=tm.getValueAt(i,j);  
////    BigInteger num2=new BigInteger(uprice);
////    BigInteger value=num1.multiply(num2);
//         JOptionPane.showMessageDialog(rootPane, quantity);     
//        }}
           
   jLabel25.setText(String.valueOf(taxs+value.intValue()));
                  
                  
      
       int  rows = jTable1.getRowCount();
 
       for(int i=0;i< jTable1.getRowCount();i++){
        for (int j=7;j<jTable1.getColumnCount();j++){
            
            jTable1.getModel().setValueAt("Edit",i,j);
        }}
        
         for(int i=0;i< jTable1.getRowCount();i++){
        for (int j=8;j<jTable1.getColumnCount();j++){
            
            jTable1.getModel().setValueAt("Delete",i,j);
        }}
       
         
          jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = jTable1.rowAtPoint(evt.getPoint());
        int col = jTable1.columnAtPoint(evt.getPoint());
        String selectedData = (String) jTable1.getValueAt(row,col);
        action(selectedData,row,col);
        
       Object t= jTable1.getModel().getValueAt(row,col);
        System.out.println(t);
        if (row >= 0 && col >= 0 && selectedData.equals("Edit")) {
         
            System.out.println(row);
            System.out.println(col);
JOptionPane.showMessageDialog(rootPane, "Edit Is selcted here");
        
////if(selectedData.equals("Delete"))
////{
////    if (JOptionPane.showConfirmDialog(null,"Are You Sure You want to delete", "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
////                     DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
////                     tm.removeRow(row);
////                     JOptionPane.showMessageDialog(rootPane, "Deleted");
////                    }
////}
        }
    }
});
 double total=0;
 double addtax=0;
        for (int i = 0;  i < rows; i++) 
 
        { 
            total += ( Double.parseDouble(jTable1.getValueAt(i, 5).toString())) ;
            addtax += ( Double.parseDouble(jTable1.getValueAt(i, 6).toString())) ;
        }
 
            jLabel21.setText(String.valueOf(total));
            jLabel22.setText(String.valueOf(addtax));
            jLabel25.setText(String.valueOf(total+addtax));
        }
        //getInvoiceID();
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(null,"Error : "+ e.getMessage(),"Error",0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void action(String datas ,int row,int col)
    {
       System.out.println(row);
       System.out.println(col);
        if(datas!="")
        {
            JOptionPane.showMessageDialog(rootPane, "Edit Is selcted here");
        } else {
        }
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//      String client=jComboBox1.getSelectedItem().toString();
//      NewClients news=new NewClients(client);
//      news.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        DateTime today = new DateTime();
        String duedate=jComboBox2.getSelectedItem().toString();
        if(duedate.equals("Net 15"))
        {
       DateTime tomorrow = today.plusDays(15);
       jDateChooser2.setDate(tomorrow.toDate());
        }
        
          if(duedate.equals("Net 30"))
        {
       DateTime tomorrow = today.plusDays(30);
       jDateChooser2.setDate(tomorrow.toDate());
        }
      
            if(duedate.equals("Net 45"))
        {
       DateTime tomorrow = today.plusDays(45);
       jDateChooser2.setDate(tomorrow.toDate());
        }
             if(duedate.equals("Net 60"))
        {
       DateTime tomorrow = today.plusDays(60);
       jDateChooser2.setDate(tomorrow.toDate());
        }
              if(duedate.equals("Net 90"))
        {
       DateTime tomorrow = today.plusDays(90);
       jDateChooser2.setDate(tomorrow.toDate());
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jDateChooser2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MouseClicked
        // TODO add your handling code here:
        jDateChooser2.setEnabled(true);
         if (evt.getClickCount() ==2 ) {
             JOptionPane.showMessageDialog(null, "Double clicked!");
             jComboBox2.setSelectedIndex(8);
        }
    }//GEN-LAST:event_jDateChooser2MouseClicked

    private void jDateChooser2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MousePressed
        // TODO add your handling code here:
        jDateChooser2.setEnabled(true);
         if (evt.getClickCount() == 1 ) {
             JOptionPane.showMessageDialog(null, "Double clicked!");
            
            jComboBox2.setSelectedIndex(8);
        }
    }//GEN-LAST:event_jDateChooser2MousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        jDateChooser2.setEnabled(true);
         if (evt.getClickCount() == 1 ) {
            jComboBox2.setSelectedIndex(7);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1FocusGained

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == evt.VK_ENTER){
//Getting pid from ptype
                //Getting pid from ptype
        String ptypes=jComboBox3.getSelectedItem().toString();
        String sql1="select pid from product where pname=?";
         try
    {
    c= ConnectionManager.getConnection();
    PreparedStatement ps=c.prepareStatement(sql1);
    ps.setString(1,ptypes);
        ResultSet rs=ps.executeQuery();
        while(rs.next())
        {
        jTextField8.setText(rs.getString(1));
        }
    }catch(Exception e)
    {
        System.out.println(e.getMessage());
    }
        
        String pid=jTextField8.getText();  
        String invoice=jTextField2.getText();  
        String issue=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String ptype=jComboBox3.getSelectedItem().toString();
        String des=jTextField3.getText();  
        String qty=jTextField4.getText();  
        String uprice =jTextField5.getText();  

    BigInteger num1=new BigInteger(qty);
    BigInteger num2=new BigInteger(uprice);
    BigInteger value=num1.multiply(num2);
    
        String tax=jComboBox4.getSelectedItem().toString();
        tax = tax.replace("%","");
        int taxes=Integer.parseInt(tax);
        float taxs=(float) (taxes * Integer.parseInt(uprice) * .01);
        
       
        System.out.println(taxs);
        String sql="insert into inventory(pid,transactiondate,invoiceno,pname,price ) values(?,?,?,?,?)";
        try
        {
        c=ConnectionManager.getConnection();
        ps=c.prepareStatement(sql);
        ps.setString(1,pid);    
        ps.setString(2, issue);  
        ps.setString(3, invoice);
        ps.setString(4,ptype); 
        ps.setString(5,uprice);
        int n=ps.executeUpdate();
        if(n==1)
        {

//            jTextField3.setText("");
//            jTextField4.setText("");
//            jTextField5.setText("");
            
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        
        int srn=tm.getRowCount()+1;

            Object[] newRow = {srn,ptype,des,qty,uprice,value,taxs};
                tm.addRow(newRow);

               jLabel19.setVisible(true);
                jLabel20.setVisible(true);
                 jLabel21.setVisible(true);
                  jLabel22.setVisible(true);;
//                  
//                    for(int i=0;i< jTable1.getRowCount();i++){
//        for (int j=5;j<jTable1.getColumnCount();j++){
//            
//            //int quantity = 
//BigInteger quantity=tm.getValueAt(i,j);  
////    BigInteger num2=new BigInteger(uprice);
////    BigInteger value=num1.multiply(num2);
//         JOptionPane.showMessageDialog(rootPane, quantity);     
//        }}
           
   jLabel25.setText(String.valueOf(taxs+value.intValue()));
                  
                  
      
       int  rows = jTable1.getRowCount();
 
       for(int i=0;i< jTable1.getRowCount();i++){
        for (int j=7;j<jTable1.getColumnCount();j++){
            
            jTable1.getModel().setValueAt("Edit",i,j);
        }}
        
         for(int i=0;i< jTable1.getRowCount();i++){
        for (int j=8;j<jTable1.getColumnCount();j++){
            
            jTable1.getModel().setValueAt("Delete",i,j);
        }}
       
         
          jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = jTable1.rowAtPoint(evt.getPoint());
        int col = jTable1.columnAtPoint(evt.getPoint());
        String selectedData = (String) jTable1.getValueAt(row,col);
        action(selectedData,row,col);
        
       Object t= jTable1.getModel().getValueAt(row,col);
        System.out.println(t);
        if (row >= 0 && col >= 0 && selectedData.equals("Edit")) {
         
            System.out.println(row);
            System.out.println(col);
JOptionPane.showMessageDialog(rootPane, "Edit Is selcted here");
        
////if(selectedData.equals("Delete"))
////{
////    if (JOptionPane.showConfirmDialog(null,"Are You Sure You want to delete", "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
////                     DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
////                     tm.removeRow(row);
////                     JOptionPane.showMessageDialog(rootPane, "Deleted");
////                    }
////}
        }
    }
});
 double total=0;
 double addtax=0;
        for (int i = 0;  i < rows; i++) 
 
        { 
            total += ( Double.parseDouble(jTable1.getValueAt(i, 5).toString())) ;
            addtax += ( Double.parseDouble(jTable1.getValueAt(i, 6).toString())) ;
        }
 
            jLabel21.setText(String.valueOf(total));
            jLabel22.setText(String.valueOf(addtax));
            jLabel25.setText(String.valueOf(total+addtax));
        }
        //getInvoiceID();
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(null,"Error : "+ e.getMessage(),"Error",0);
        }
         }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         String client=jComboBox1.getSelectedItem().toString();
        
        
        if(client.equals("-----Select Client Type-----"))
        {
        
        JOptionPane.showMessageDialog(rootPane, "Please Select a client for Your Invoice");
        //jButton2.setEnabled(false);
        }
        else{
        jButton2.setEnabled(true);
        String invoice=jTextField2.getText();
        String issue=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String ponumber=jTextField1.getText();
        String payterm=jComboBox2.getSelectedItem().toString();
        String duedate=((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
        String producttype=jComboBox3.getSelectedItem().toString();
        String des=jTextField3.getText();
        String qty=jTextField4.getText();
        String uprice=jTextField5.getText();
        String tax=jComboBox4.getSelectedItem().toString();
        String subtotal=jLabel21.getText();
        String gtax=jLabel22.getText();
        String total=jLabel25.getText();
        //Report Generation
        String billto=(jComboBox1.getSelectedItem())+"\n"+jLabel18.getText();
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection c= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/invent","root","root");
            String REPORT="C:\\Users\\Nitin Singla\\Documents\\NetBeansProjects\\Inventory System\\src\\final.jrxml";
            JasperReport Jasp=JasperCompileManager.compileReport(REPORT);
            Map parametersMap = new HashMap();  
         
            parametersMap.put("invoice",invoice);
            parametersMap.put("billto",billto);
            parametersMap.put("amount","4");
            parametersMap.put("subtotal",subtotal);
            parametersMap.put("gtax",gtax);
            parametersMap.put("total",total);
            
            JasperPrint jp=JasperFillManager.fillReport(Jasp,parametersMap,c);
            JasperViewer.viewReport(jp,false);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1FocusLost

    public void display()
    {
    try
        {
            String sql = "select * from bqueue";
            c = ConnectionManager.getConnection();
            ps = c.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            while(tm.getRowCount()>0)
            {
                tm.removeRow(0);
            }
            while(rs.next())
            {  
                Object[] newRow = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getInt(4)};
                tm.addRow(newRow);
            }
         
        }catch(Exception e)
        {
            e.printStackTrace();
        }
  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceNew().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
